version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/nodejs-api:staging
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=staging
      - STAGING_MONGO_URI=mongodb://mongodb:27017/nodejs-api-staging
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - staging-network

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_staging_data:/data/db
    restart: unless-stopped
    networks:
      - staging-network

networks:
  staging-network:
    driver: bridge

volumes:
  mongodb_staging_data: 