version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEV_MONGO_URI=mongodb://mongodb:27017/nodejs-api-dev
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - development-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    restart: unless-stopped
    networks:
      - development-network

networks:
  development-network:
    driver: bridge

volumes:
  mongodb_dev_data: 